# Generated by Django 5.1.3 on 2024-11-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kitty', max_length=100)),
                ('age', models.PositiveIntegerField(default=1)),
                ('satiety', models.PositiveIntegerField(default=40)),
                ('happiness', models.PositiveIntegerField(default=40)),
                ('sleeping', models.BooleanField(default=False)),
                ('mood', models.CharField(default='neutral', max_length=50)),
            ],
        ),
    ]
